### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-baranov#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
2) Відомо, що Git-система контроля версій використовує поняття “гілка” (branch). 
Поясніть, будь ласка, як використання такої “гілки” 
може підвищити безпеку процесів створення програмного продукту?

**Comment by deawer** [comment]
Використання гілок в Git підвищує безпеку процесів створення програмного продукту, оскільки:
- Вони ізолюють функціональність і дозволяють розробникам працювати над різними частинами коду окремо
- Дозволяють швидко реагувати на виявлені безпекові проблеми, створюючи окремі гілки для виправлень
- Допомагають вести аудит і перевірку коду без впливу на основну гілку
- Забезпечують спостереження за змінами та спрощують виправлення помилок

В результаті, гілки полегшують керування розробкою та підвищують безпеку продукту.
